services:
  api-dev:
    image: node:18-alpine
    container_name: tcc_api_dev
    working_dir: /app
    command: sh -c "npm install --legacy-peer-deps && npm run start:dev"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: tcc
      DB_PASS: tcc
      DB_NAME: tcc
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    profiles: ["dev"]

  web-vue-dev:
    image: node:18-alpine
    container_name: tcc_web_vue_dev
    working_dir: /app
    command: sh -c "npm install --legacy-peer-deps && npm run dev -- --host 0.0.0.0 --port 8081"
    volumes:
      - ./frontend-vue:/app
    depends_on:
      - api-dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "8081:8081"
    profiles: ["dev-vue"]

  web-react-dev:
    image: node:18-alpine
    container_name: tcc_web_react_dev
    working_dir: /app
    command: sh -c "npm install --legacy-peer-deps && npm run dev -- --host 0.0.0.0 --port 8082"
    volumes:
      - ./frontend-react:/app
    depends_on:
      - api-dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "8082:8082"
    profiles: ["dev-react"]
