version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: tcc_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tcc
      MYSQL_USER: tcc
      MYSQL_PASSWORD: tcc
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: ./backend
    container_name: tcc_api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: tcc
      DB_PASS: tcc
      DB_NAME: tcc
    ports:
      - "3000:3000"

  web-vue:
    build: ./frontend-vue
    container_name: tcc_web_vue
    depends_on:
      - api
    ports:
      - "8081:80"
    profiles: ["vue"]

  web-react:
    build: ./frontend-react
    container_name: tcc_web_react
    depends_on:
      - api
    ports:
      - "8082:80"
    profiles: ["react"]

volumes:
  db_data:
